#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BulletMLLibQuickStart.Android.Resource", IsApplication=true)]

namespace BulletMLLibQuickStart.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BulletMLLib.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::BulletMLLib.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::Equationator.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::Equationator.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::FilenameBuddy.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::FilenameBuddy.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::FontBuddyLib.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::FontBuddyLib.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::GameTimer.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::GameTimer.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::HadoukInput.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::HadoukInput.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::MatrixExtensions.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::MatrixExtensions.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::RandomExtensions.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::RandomExtensions.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::Vector2Extensions.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::Vector2Extensions.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
			global::XmlBuddy.Android.Resource.String.ApplicationName = global::BulletMLLibQuickStart.Android.Resource.String.ApplicationName;
			global::XmlBuddy.Android.Resource.String.Hello = global::BulletMLLibQuickStart.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
